from .deeplab import *  # noqa
from .dfnet_decoder import *  # noqa
from .sfnet import *  # noqa
from .unet_decoder import *  # noqa
from .pspnet import *  # noqa
from .biseg import *  # noqa
from .icnet import *  # noqa
from .semantic_fpn import *  # noqa
from .segformer_decoder import * # noqa
from .ocrnet import * # noqa
